### POST ALL
POST http://localhost:8080/api/customer
Content-Type: application/json

{
    "name":{
        "first_name":"Aditya",
        "last_name":"Sharma"
    },
    "store_visited":[{
        "id":"6039d78c62c0570a18de58ca",
        "name":"Store 2"
    }],
    "total_purchase":{
        "amount":12343
    },
    "contact_details":{
        "primary_number":123123123,
        "email":"nitinverma@gmail.com",
        "address":{
            "full":"2190/11 faridabad, Haryana",
            "state":"Haryana",
            "city":"faridabad",
            "pincode":12323
        }
    }
}