### GET ALL
POST http://localhost:8080/api/role
Content-Type: application/json

{
    "name": "test",
    "product": {},
    "store": {},
    "user": {},
    "customer": {},
    "supplier": {},
    "productCategory": {},
    "role":{}
}