### ADD / EDIT
POST http://localhost:8080/api/product
Content-Type: application/json

{
    "name":"Xiaomi Redmi Note 10 Pro",
    "sku":"xrn10p",
    "category":{
        "id":"60408b3b1aec2e0015418bee"
    },
    "dimension":{
        "weight":20,
        "height":30,
        "length":23,
        "width":12
    },
    "suppliers":[
        {
            "id":"604caf8d256d2600156fb68a"
        }
    ],
    "stores":[
        {
            "id":"6040c1cd5c8da00015536bdh",
            "stock":{
                "currentStock":3000,
                "openingStock":4000
            }
        },
        {
            "id":"6040c1cd5c8da00015536bdi",
            "stock":{
                "currentStock":3000,
                "openingStock":4000
            }
        },
        {
            "id":"6040c1cd5c8da00015536bdf",
            "stock":{
                "currentStock":7000,
                "openingStock":4000
            }
        }
    ],  
    "manufacturer":"manufacturer",
    "brand":"brand",
    "sale_price":23,
    "current_price":45,
    "buying_price":26
}