### GET ALL
GET http://localhost:8080/api/productCategory

### GET by name
GET http://localhost:8080/api/productCategory?name=abcde

### search
GET http://localhost:8080/api/productCategory?query=a
### GET WITH NAME
GET http://localhost:8080/api/productCategory


