### ADD / EDIT
POST http://localhost:8080/api/product
Content-Type: application/json

{
    "name":"Resdas s1 Chiefs Chief Shoes",
    "sku":"lkssdssdsads",
    "category":{
        "id":"604089641aec2e0015418be2",
        "name":"Nike Cap"
    },
    "dimension":{
        "weight":20,
        "height":30,
        "length":23,
        "width":12
    },
    "suppliers":[
        {
            "name":"nike ads",
            "id":"6041d82456eb0500150c8181"
        }
    ],
    "stores":[

    ],
    "manufacturer":"manufacturer",
    "brand":"brand",
    "sale_price":23,
    "current_price":45,
    "buying_price":26
}