### ADD / EDIT
POST http://localhost:8080/api/product
Content-Type: application/json

{
    "name":"Samsung Galaxy S4ass2",
    "sku":"sgt3d10",
    "category":{
        "id":"604089641aec2e0015418be2"
    },
    "manufacturer":"Samsung",
    "brand":"Samsung",
    "dimension":{
        "weight":230,
        "height":290,
        "length":240,
        "width":200
    },
    "sale_price":3200,
    "current_price":3200,
    "buying_price":3200,
    
    "suppliers":[
        {
        "id":"604caf8d256d2600156fb68a"
        },
        {
        "id":"604cb113256d2600156fb691"
        },
        {
            "id" : "604caf8d256d2600156fb68a"
                    },
        {
        "id" : "604cb113256d2600156fb691"
        },
        {
            "id" : "604cb21b256d2600156fb694"
        }
    ]
}


### ADD / EDIT
POST http://localhost:8080/api/product
Content-Type: application/json

{
    "name":"Samsung Galaxy m42",
    "sku":"frt134",
    "category":{
        "id":"604089641aec2e0015418be2"
    },
    "manufacturer":"Samsung",
    "brand":"Samsung",
    "dimension":{
        "weight":230,
        "height":290,
        "length":240,
        "width":200
    },
    "sale_price":3200,
    "current_price":3200,
    "buying_price":3200,
    "suppliers":[
        {
        "id":"604caf8d256d2600156fb68a"
        },
        {
        "id":"604cb113256d2600156fb691"
        },
        {
        "id" : "604cb21b256d2600156fb694"
        }
    ],
    "stores":[
        {
            "id": "6040c1cd5c8da00015536bdf",
            "stock" : {
               "currentStock" : 6422,
               "openingStock" : 9876
            }
        }
    ]
}















