### GET ALL
GET http://localhost:8080/api/product
### GET ALL
GET http://localhost:8080/api/product?id=604089ea1aec2e0015418beb
### GET NAME
GET http://localhost:8080/api/product?name=Nike Cap
### GET Partial Search
GET http://localhost:8080/api/product?query=Red