### GET ALL
GET http://localhost:8080/api/product
### GET ALL
GET http://localhost:8080/api/product?id=6040a4bf5c8da00015536b73
### GET NAME
GET http://localhost:8080/api/product?name=addidas Cap
### GET Partial Search
GET http://localhost:8080/api/product?query=Red

