POST http://localhost:80/api/supplier
Content-Type: application/json

{
    "company_name":"Sjjsd",
    "name":{
        "first_name":"jhssdsdsfsksjfd",
        "last_name":"sljdsdfdsf"
    },
    "contact_details":{
        "primary_number":1212313,
        "secondary_number":1212313,
        "email":"anthonyfinxi@gmail.com",
        "address":{
            "city":"faridabad",
            "state":"Haryana"
        }
    },
    "active":true,
    "total_purchase":3432
}