POST http://localhost:8000/api/supplier
Content-Type: application/json

{
    "id":"607f27ad9d42e24ac47c031b",
    "company_name":"DTDC",
    "name":{
        "first_name":"Ramesh",
        "last_name":"Nayar"
    },
    "contact_details": {
      "address": {
        "full": "Shop No-132, near Singh Sabha Gurudwara, Sector 15, Faridabad, Haryana",
        "city": "Faridabad",
        "state": "14863",
        "pincode":123123
      },
      "primary_number": 9818031042,
      "email": "support@amanturbanhouse.com"
    }
}