POST http://localhost:8080/register
Content-Type: application/json

{
    "name":
    {
        "first_name":"Anthony",
        "last_name":"Finix"
    },
    "username":"anthonyfinix",
    "password":"anthonyfinix@123",
    "contact_details":{
        "primary_number":9818031042,
        "email":"anthonyfinix@gmail.com",
        "address":{
            "full":"2190, sector 8, faridabad, Haryana",
            "city":"faridabad",
            "state":"Haryana",
            "coordinates":[
                28.392406,77.340799
            ]
        }
    },
    "role":"Admin",
    "assigned_store":{
        "id":"1232131",
        "name":"store1"
    }
}