### CREATE
POST http://localhost:8000/api/customer
Content-Type: application/json

{
    "name": {
        "first_name": "Customer",
        "middle_name": "Anthony",
        "last_name": "Finix"
    },
    "contact_details": {
        "primary_number": 2342234234,
        "email": "anthonyfinix@gmail.com",
        "address": {
            "full": "2190/7A Faridabad, Haryana 121006",
            "city": "Faridabad",
            "state": "Haryana",
            "coordinates": [],
            "pincode":13232
        }
    },
    "store_visited":["60645bfbb07fb70015e14e4f"],
    "total_purchase":{
        "amount":200
    }
}