### CREATE
POST http://localhost:8000/api/purchase
Content-Type: application/json

{
    "store":"60645bfbb07fb70015e14e4f",
    "product":[{"id":"607f2395f680fc3b70aaa748","qty":3}],
    "customer":{
        "id":"60645403b2de2f00159f1e02",
        "name": {
        "first_name": "Customer",
        "middle_name": "Anthony",
        "last_name": "Finix"
        },
        "contact_details": {
            "primary_number": 2342234234,
            "email": "anthonyfinix@gmail.com",
            "address": {
                "full": "2190/7A Faridabad, Haryana 121006",
                "city": "Faridabad",
                "state": "Haryana",
                "coordinates": [],
                "pincode":13232
            }
        }
    },
    "amount":{
        "total":300
    }
}