### GET ALL
POST http://localhost:8000/api/purchase
Content-Type: application/json

{
    "id" : "609f8bddf9398d2a64495595",
    "store": "6039d78c62c0570a18de58ca",
   

    "customer":{
        "id":"606453eab2de2f00159f1dfe"
    },
    "amount":{
        
        "total" :7000
    },
    "products":[
        {
            "qty":5,
            "product":"603342c7ef006b1c1c16f5d6"
    
        }
    ]

}