### ADD / EDIT
POST http://localhost:8080/api/product
Content-Type: application/json

{
    "id":"608678f758eb792ba0b82d99",
    "name":"Xiaomi Redmi Note 10 Pro",
    "sku":"xrn10p",
    "category":{
        "id":"608674e958eb792ba0b82d7d"
    },
    "dimension":{
        "weight":20,
        "height":30,
        "length":23,
        "width":12
    },
    "suppliers":[
        {
            "id":"6086760958eb792ba0b82d80"
        }
    ],
    "stores":[
        {
            "id":"608674b958eb792ba0b82d74",
            "stock":{
                "currentStock":3000,
                "openingStock":4000
            }
        }
    ],  
    "manufacturer":"manufacturer",
    "brand":"brand",
    "sale_price":23,
    "current_price":45,
    "buying_price":26
}