### ADD / EDIT
POST http://localhost:8000/api/product
Content-Type: application/json

{
    "id":"607f2395f680fc3b70aaa748",
    "name":"MI Xiaomi Redmi Note 10 Pro",
    "sku":"xrn10ph",
    "category":{
        "id":"608674e958eb792ba0b82d7d"
    },
    "dimension":{
        "weight":200,
        "height":300,
        "length":230,
        "width":120
    },
    "suppliers":[
        {
            "id":"607f27ad9d42e24ac47c031b"
        },
        {
            "id":"607f25009d42e24ac47c02e6"
        }
    ],
    "stores":[
        {
            "id":"60645bfbb07fb70015e14e4f",
            "stock":{
                "currentStock":300,
                "openingStock":400
            }
        },
        {
            "id":"60645becb07fb70015e14e4b",
            "stock":{
                "currentStock":300,
                "openingStock":400
            }
        }
    ],  
    "manufacturer":"manufacturer",
    "brand":"brand",
    "sale_price":23,
    "current_price":45,
    "buying_price":26
}