### ADD / EDIT
POST http://localhost:8080/register
Content-Type: application/json

{
    "name":{
        "first_name":"Anthony",
        "last_name":"Finix"
    },
    "username":"anthonyfinix@gmail.com",
    "password":"anthonyfinix@1234",
    "contact_details":{
        "primary_number":123123123,
        "email":"nitinverma@gmail.com",
        "address":{
            "full":"2190/11 faridabad, Haryana",
            "state":"Haryana",
            "city":"faridabad",
            "pincode":12323
        }
    }
}